version: 2
updates:
  # ğŸ” SECURITY UPDATES â€” DAILY
  - package-ecosystem: 'npm'
    directory: '/' # root of the project
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'direct'
    labels:
      - 'security'
    insecure-external-code-execution: allow
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'eslint'
        versions: ['<8.0.0']

  # ğŸ”§ REGULAR DEPENDENCIES â€” WEEKLY
  - package-ecosystem: 'npm'
    directory: '/' # root of the project
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'direct'
    labels:
      - 'dependencies'
    ignore:
      - dependency-name: 'eslint'
        versions: ['<8.0.0']
